# Generated by Django 5.2 on 2025-04-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
